"""
Django settings for digitalarz project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from django.contrib import messages
from django.contrib.auth import get_user_model
# from django.contrib.auth.models import User
from django.urls import reverse_lazy

from digitalarz.localsettings import *

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
SITE_ID = 1
SITE_NAME = 'DigitalArz'
# SITE_URL = 'localhost:3333'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gm3ewwu8rzi(kzow6&4o9oqkeg#6rr=skgp48yhp(9hj9hce&o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
CORS_ORIGIN_WHITELIST = []
CORS_ORIGIN_ALLOW_ALL = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.gis',

    'corsheaders',
    'simple_history',
    'bootstrap4',
    'fontawesome_5',

    'digitalarz',
    'spatial_app',
    'spatial_app.layer',
    'spatial_app.map'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'digitalarz.middleware.current_user.CurrentUserMiddleware',
    'digitalarz.middleware.error_handlers.HandleBusinessExceptionMiddleware'
]

ROOT_URLCONF = 'digitalarz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'digitalarz.context_processors.add_base_navbar_items_to_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'digitalarz.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
AUTH_USER_MODEL = 'auth.user'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'ferrp_admin': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'ferrp_admin',
        'USER': DB_USER,
        'HOST': DB_HOST,
        'PASSWORD': DB_PASSWORD,  # 'postr2vdhagres', 'postgres'
        'PORT': DB_PORT,
    },
    'spatialds': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'ferrp_data',
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,  # 'postr2vdhagres', 'postgres'
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}
# proxy_read_timeout = 1000
DATABASE_ROUTERS = ['digitalarz.routers.multi_database_router']
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}
# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, "static_root")
STATICFILES_DIRS = [os.path.join(PROJECT_ROOT, 'static')]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

FIXTURE_PATH = os.path.join(PROJECT_ROOT, "fixtures/")
# FIXTURE_DIRS =(os.path.join(PROJECT_ROOT, "fixtures/"))
LOGIN_URL = reverse_lazy('login')
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_PASSWORD = 'puathcitash1@3'
EMAIL_HOST_USER = 'pucit.atherashraf@gmail.com'
EMAIL_PORT = 465  # 587
EMAIL_USE_TLS = True

GEOS_LIBRARY_PATH = os.environ.get('GEOS_LIBRARY_PATH')
GDAL_LIBRARY_PATH = os.environ.get('GDAL_LIBRARY_PATH')

# --- When using Postgres as default database to use django.contrib.postgres.JSONField
# USE_NATIVE_JSONFIELD = True
