# Generated by Django 2.2.5 on 2019-10-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=600)),
                ('params', models.TextField()),
                ('created_by', models.CharField(max_length=200)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('created_time', models.TimeField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
